### ISSUE TITLE
I would call it a letter..

### ISSUE THREAD

**Issue by wimrew** [daj/legs-or-hotdogs-images#1]
Hi!

It’s not really an issue, just that messaging was disabled in Github a while ago..
I am (among others) a Hololens developer. I got excited when I read your Android-Tensorflow retraining tutorial because I am working on a project that would make possible to learn (and recognize) deaf sign language using the Hololens. 
When I read your tutorial, I was thinking, I could just teach the model all the signs, and just pass data (screenshot-recognized label) between the Hololens and a running Android app. The Hololens part is all good, but I hit a little bump while following your tutorial, hence the letter. As a couple others also mentioned, sometimes the directory structure after the build process seems to be different than the one you anticipated. (no android\Assets directory) I tried to grab the assets manually (there is a zip file which contains the model file+labels), but you used a different naming pattern for your model, meaning you also had to modify the internal wiring, to get the connections right.. Anyway, do you have an idea what could’ve gone wrong? It would be quite interesting to see a Hololens recognizing sign language.. I would like to make it work. :)

Best,
Imre

**Comment by daj** [comment]
That sounds like a cool project. :-) I'm not sure what went wrong for you, but you could take another look at my tutorial as I've been making some updates?  It seems like the most common problem is that people forget to change between their Docker container and their local machine (I've tried to make it more obvious when this is necessary).  You could also watch the TensorFlow For Poets tutorial to get ideas.

**Comment by wimrew** [comment]
Hi,
I managed to solve it in a different way, though I used some of your ideas. In the end it got more close to the corporate life, I recognize different tools, engines, etc.
You need a slightly different strategy to recognize sign language, as you first need to crop out (/other strategy) the hand from the image. If not, the difference between the sign-classes won't be significantly big.
God job with the tutorial, the ideas helped a lot!
